apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb-cs-pm1
  name: mariadb-cs-pm1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb-cs-pm1
    spec:
      hostname: mariadb-cs-pm1
      containers:
      - name: pm1
        image: alphatoxic/mariadb-kubernetes:latest
        args: ["./entrypoint.sh"]
        resources: {}
      - name: node-explorer
        image: prom/node-exporter:latest
        resources: {}
      restartPolicy: Always
status: {}
