apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb-cs-um
  name: mariadb-cs-um
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb-cs-um
    spec:
      hostname: mariadb-cs-um

      containers:
      - name: um
        image: alphatoxic/mariadb-kubernetes:latest
        args: ["./entrypoint2.sh"]
        volumeMounts:
        - name: shared-data-log
          mountPath: /var/log/mariadb/columnstore
        resources: {}

      - name: node-exporter
        image: prom/node-exporter:latest
        resources: {}

      - name: fluentd
        image: fluent/fluentd:latest
        resources: {}
        volumeMounts:
        - name: fluentd-config-vol
          mountPath: /fluentd/etc/
        - name: shared-data-log
          mountPath: /var/log/mariadb/columnstore

      volumes:
        - name: fluentd-config-vol
          configMap:
            name: fluentd-config
        - name: shared-data-log
          emptyDir: {}

      restartPolicy: Always
status: {}
