apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: prometheus
    spec:
      hostname: prometheus
      containers:
      - image: prom/prometheus:latest
        name: prometheus
        resources: {}
        volumeMounts:
        - name: prometheus-config-vol
          mountPath: /etc/prometheus

      volumes:
        - name: prometheus-config-vol
          configMap:
            name: prometheus-config

      restartPolicy: Always
status: {}
