version: '3'
services:
  galera1:
    hostname: galera1
    build:
      context: ./galera/
    command: ./entrypoint.sh
    container_name: galera1
    environment:
      - MAIN_NODE=true
      - MYSQL_PASS=${MYSQL_PASS}

  galera2:
    hostname: galera2
    build:
      context: ./galera/
    command: ./entrypoint.sh
    container_name: galera2
    depends_on:
      - galera1

  galera3:
    hostname: galera3
    build:
      context: ./galera/
    command: ./entrypoint.sh
    container_name: galera3
    depends_on:
      - galera1

  maxscale:
    hostname: maxscale
    image: mariadb/maxscale:latest
    command: maxscale -d -U maxscale --configdir=/etc/maxscale-cfg
    volumes:
      - "./maxscale:/etc/maxscale-cfg/"
    container_name: maxscale
    environment:
      - MYSQL_PASS=${MYSQL_PASS}
    depends_on:
      - galera1
      - galera2
      - galera3