version: '3'
services:
  galera-0:
    hostname: galera-0
    build:
      context: ./galera/
    command: ./entrypoint.sh
    container_name: galera-0
    environment:
      - MAIN_NODE=true
      - MYSQL_PASS=${MYSQL_PASS}

  galera-1:
    hostname: galera-1
    build:
      context: ./galera/
    command: ./entrypoint.sh
    container_name: galera-1
    depends_on:
      - galera-0

  galera-2:
    hostname: galera-2
    build:
      context: ./galera/
    command: ./entrypoint.sh
    container_name: galera-2
    depends_on:
      - galera-0

  maxscale:
    hostname: maxscale
    image: mariadb/maxscale:latest
    command: maxscale -d -U maxscale --configdir=/etc/maxscale-cfg
    volumes:
      - "./maxscale:/etc/maxscale-cfg/"
    container_name: maxscale
    environment:
      - MYSQL_PASS=${MYSQL_PASS}
    depends_on:
      - galera-0
      - galera-1
      - galera-2