# Headless service for stable DNS entries for StatefulSet members
apiVersion: v1
kind: Service
metadata:
  name: mariadb-cluster
  labels:
    app: mariadb-galera-cluster
spec:
  ports:
  - name: mariadb
    port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    app: mariadb-galera-cluster
---
# a StatefulSet for the galera cluster
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: galera
spec:
  selector:
    matchLabels:
      app: mariadb-galera-cluster
  serviceName: mariadb-cluster
  replicas: 3
  template:
    metadata:
      labels:
        app: mariadb-galera-cluster
    spec:
      containers:
      - name: galera
        image: alphatoxic/mariadb-kubernetes:galera_latest
        command:
        - bash
        - ./entrypoint.sh
        env:
        - name: MYSQL_PASS
          value: "pass"
        ports:
        - containerPort: 3306
        - containerPort: 22
        - containerPort: 4567
        - containerPort: 4568
        - containerPort: 4444
        - containerPort: 9100
        resources: {}
        volumeMounts:
        - name: mariadb-galera-data-vol
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: shared-data-log
          mountPath: /var/log/mysql
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1

      - name: mysqld-exporter
        image: prom/mysqld-exporter:latest
        env:
        - name: DATA_SOURCE_NAME
          value: 'root:pass@(galera1:3306)/'
        resources: {}

      - name: fluentd
        image: fluent/fluentd:latest
        resources: {}
        volumeMounts:
        - name: fluentd-config-vol
          mountPath: /fluentd/etc/
        - name: shared-data-log
          mountPath: /var/log/mysql

      volumes:
      - name: fluentd-config-vol
        configMap:
          name: fluentd-config-tx
      - name: shared-data-log
        emptyDir: {}

      restartPolicy: Always

  volumeClaimTemplates:
  - metadata:
      name: mariadb-galera-data-vol
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
