apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: galera3
  name: galera3
spec:
  clusterIP: "None"
  ports:
  - name: "22"
    port: 22
    targetPort: 22
  - name: "3306"
    port: 3306
    targetPort: 3306
  - name: "4567"
    port: 4567
    targetPort: 4567
  - name: "4568"
    port: 4568
    targetPort: 4568
  - name: "4444"
    port: 4444
    targetPort: 4444
  - name: "9100"
    port: 9100
    targetPort: 9100
  - name: "9104"
    port: 9104
    targetPort: 9104
  selector:
    io.kompose.service: galera3
status:
  loadBalancer: {}
