apiVersion: v1
kind: Service
metadata:
  name: {{APPLICATION}}-{{ENVIRONMENT}}-mcs-sandbox-zepp
  labels:
    mariadb: {{APPLICATION}}-{{ENVIRONMENT}}
spec:
  ports:
  - name: zeppelin
    port: 8080
    targetPort: 8080
  selector:
    mariadb: {{APPLICATION}}-{{ENVIRONMENT}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{APPLICATION}}-{{ENVIRONMENT}}-mdb-zepp
spec:
  selector:
    matchLabels:
      mariadb: {{APPLICATION}}-{{ENVIRONMENT}}
  serviceName: {{APPLICATION}}-{{ENVIRONMENT}}-mdb-clust
  replicas: 1
  template:
    metadata:
      labels:
        mariadb: {{APPLICATION}}-{{ENVIRONMENT}}
    spec:
      initContainers:
      - name: init-mdb-zeppelin
        image: mariadb/columnstore_zeppelin:latest
        command:
          - bash
          - /mnt/config-template/init-configurations.sh
          - zeppelin
        volumeMounts:
          - mountPath: /mnt/secrets
            name: mariadb-secrets-vol
            readOnly: true
          - mountPath: /docker-entrypoint-initdb.d
            name: mariadb-entrypoint-vol
          - mountPath: /mnt/config-template
            name: mariadb-configtemplate-vol
          - mountPath: /mnt/config-map
            name: mariadb-config-vol
          - name: notebook
            mountPath: /zeppelin/notebook
      containers:
      - image: nastybuff/zeppelin:latest
        name: mdb-zeppelin
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - name: mariadb-entrypoint-vol
          mountPath: /docker-entrypoint-initdb.d
        - name: mariadb-config-vol
          mountPath: /mnt/config-map
        - name: notebook
          mountPath: /zeppelin/notebook

      restartPolicy: Always
      volumes:
      - name: mariadb-entrypoint-vol 
        emptyDir: {}
      - name: mariadb-config-vol
        emptyDir: {}
      - name: mariadb-configtemplate-vol
        configMap:
          name: mariadb-config
      - name: mariadb-secrets-vol
        secret:
          secretName: {{APPLICATION}}-{{ENVIRONMENT}}-mariadb-secret
  volumeClaimTemplates:
  - metadata:
      name: notebook
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi