apiVersion: v1
kind: Service
metadata:
  name: {{MARIADB-LABEL}}-mariadb
  labels:
    mariadb: {{MARIADB-LABEL}}
    endpoint.mariadb: {{MARIADB-LABEL}}
spec:
  ports:
  - name: maxscale-readwrite
    port: 4006
    targetPort: 4006
  - name: maxscale-readonly
    port: 4008
    targetPort: 4008
  selector:
    maxscale.mariadb: {{MARIADB-LABEL}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{MARIADB-LABEL}}-mdb-mxs
  labels:
    mariadb: {{MARIADB-LABEL}}
    maxscale.mariadb: {{MARIADB-LABEL}}
spec:
  selector:
    matchLabels:
      maxscale.mariadb: {{MARIADB-LABEL}}
  replicas: 2
  template:
    metadata:
      labels:
        maxscale.mariadb: {{MARIADB-LABEL}}
    spec:
      initContainers:
      - name: init-maxscale
        image: mariadb:10.3
        command:
          - bash
          - /mnt/config-template/init-configurations.sh
          - maxscale
        volumeMounts:
          - mountPath: /mnt/secrets
            name: mariadb-secrets-vol
            readOnly: true
          - mountPath: /mnt/config-template
            name: mariadb-configtemplate-vol
          - mountPath: /etc/maxscale-cfg
            name: mariadb-config-vol
      containers:
      - image: node:alpine
        command: ["/bin/sh"]
        args: ["-c", "cd /root; tar xzf /mnt/config-template/state-store.tar.gz; node ./client.js maxscale {{MARIADB-LABEL}}-mdb-state"]
        imagePullPolicy: IfNotPresent
        name: state
        volumeMounts:
          - name: mariadb-configtemplate-vol
            mountPath: /mnt/config-template
      - args:
        - maxscale
        - -d
        - -U
        - maxscale
        - --configdir=/etc/maxscale-cfg
        image: mariadb/maxscale:latest
        name: maxscale
        ports:
        - containerPort: 4006
        - containerPort: 4008
        resources: {}
        volumeMounts:
        - mountPath: /etc/maxscale-cfg
          name: mariadb-config-vol
      restartPolicy: Always
      volumes:
      - name: mariadb-config-vol
        emptyDir: {}
      - name: mariadb-configtemplate-vol
        configMap:
          name: mariadb-config
      - name: mariadb-secrets-vol
        secret:
          secretName: {{MARIADB-LABEL}}-mariadb-secret
