apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mariadb-test-perf
  labels:
    mariadb: {{ .Release.Name }}
    test.perf.mariadb: {{ .Release.Name }}
    {{- if .Values.mariadb.cluster.id }}
    id.mariadb: "{{ .Values.mariadb.cluster.id }}"
    {{- end }}
    {{- if .Values.mariadb.cluster.labels }}
{{ toYaml .Values.mariadb.cluster.labels | indent 4 }}
    {{- end }}
    {{- if .Values.mariadb.test.perf.labels }}
{{ toYaml .Values.mariadb.test.perf.labels | indent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      test.perf.mariadb: {{ .Release.Name }}
  replicas: {{ .Values.mariadb.test.perf.replicas }}
  template:
    metadata:
      labels:
        mariadb: {{ .Release.Name }}
        test.perf.mariadb: {{ .Release.Name }}
      {{- if or (.Values.mariadb.cluster.annotations) (.Values.mariadb.test.perf.annotations) }}
      annotations:
      {{- end }}
      {{- if .Values.mariadb.cluster.annotations }}
{{ toYaml .Values.mariadb.cluster.annotations | indent 8 }}
      {{- end }}
      {{- if .Values.mariadb.test.perf.annotations }}
{{ toYaml .Values.mariadb.test.perf.annotations | indent 8 }}
      {{- end }}
    spec:
      containers:
      - name: mdb-sysbench
        image: {{ .Values.mariadb.test.perf.image }}
        imagePullPolicy: Always
        {{- if or (.Values.mariadb.test.perf.resources.limits.cpu) (.Values.mariadb.test.perf.resources.limits.memory) (.Values.mariadb.test.perf.resources.requests.cpu) (.Values.mariadb.test.perf.resources.requests.memory) }}
        resources:
        {{- end }}
          {{- if or (.Values.mariadb.test.perf.resources.requests.cpu) (.Values.mariadb.test.perf.resources.requests.memory) }}
          requests:
          {{- end }}
            {{- if .Values.mariadb.test.perf.resources.requests.cpu }}
            cpu: {{ .Values.mariadb.test.perf.resources.requests.cpu }}
            {{- end }}
            {{- if .Values.mariadb.test.perf.resources.requests.memory }}
            memory: {{ .Values.mariadb.test.perf.resources.requests.memory }}
            {{- end }}
          {{- if or (.Values.mariadb.test.perf.resources.limits.cpu) (.Values.mariadb.test.perf.resources.limits.memory) }}
          limits:
          {{- end }}
            {{- if .Values.mariadb.test.perf.resources.limits.cpu }}
            cpu: {{ .Values.mariadb.test.perf.resources.limits.cpu }}
            {{- end }}
            {{- if .Values.mariadb.test.perf.resources.limits.memory }}
            memory: {{ .Values.mariadb.test.perf.resources.limits.memory }}
            {{- end }}