# Copyright (C) 2018, MariaDB Corporation
#
# Stores cluste-wide initialization scripts in a config map

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.LABEL }}-mariadb-config
  labels:
    mariadb: {{ .Values.LABEL }}
    mariadb.id: "{{ .Values.ID }}"
data:
  init-configurations.sh: |
{{ .Files.Get "config/tx/init-configurations.sh" | indent 4 }}

  start-mariadb-instance.sh: |
{{ .Files.Get "config/tx/start-mariadb-instance.sh" | indent 4 }}

  maxscale.cnf: |
{{ tpl (.Files.Get "config/tx/maxscale.cnf") . | indent 4 }}

  users.sql: |
{{ tpl (.Files.Get "config/tx/users.sql") . | indent 4 }}

  replication.sql: |
{{ tpl (.Files.Get "config/tx/replication.sql") . | indent 4 }}
