apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-mdb-backup-job
  labels:
{{ tpl (.Files.Get "snippets/labels") . | indent 4 }}
    backup-job.mariadb: {{ .Release.Name }}
{{ tpl (.Files.Get "snippets/annotations") . | indent 2}}
spec:
  schedule: "{{ .Values.mariadb.backup.schedule }}"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      backoffLimit: 1

      template:
        spec:
          containers:
          - name: backup-job
            image: {{ .Values.mariadb.backup.image }}
            command:
              - python3
              - /python/backup/call.py
            imagePullPolicy: Always
            env:
            - name: RELEASE_NAME
              value: {{ .Release.Name }}
            - name: CLUSTER_TOPOLOGY
              value: {{ .Values.mariadb.cluster.topology }}
            volumeMounts:
            - name: mariadb-secrets-vol
              mountPath: "/etc/hmac_secret"
              readOnly: true

          restartPolicy: Never

          volumes:
          - name: mariadb-secrets-vol
            secret:
              secretName: {{ .Release.Name }}-mariadb-secret
