# Copyright (C) 2018, MariaDB Corporation
#
# Defines a galera configuration in a StatefulSet behind
# a headless service. Allows scaling the number of server instances
# by using:
# kubectl scale sts <label>-mdb-galera --replicas=<number of server instances>

# Headless service for stable DNS entries for StatefulSet members
{{ tpl (.Files.Get "snippets/external-service") . }}
---
# a StatefulSet for the galera cluster
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mdb-galera
  labels:
{{ tpl (.Files.Get "snippets/labels") . | indent 4 }}
    server.mariadb: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      server.mariadb: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}-mdb-clust
  replicas: {{ .Values.mariadb.server.replicas }}
  template:
    metadata:
      labels:
{{ tpl (.Files.Get "snippets/labels") . | indent 8 }}
        server.mariadb: {{ .Release.Name }}
{{ tpl (.Files.Get "snippets/annotations") . | indent 6 }}
    spec:
      initContainers:
      # runs a state store client to determine the IP of the active galera
      - name: init-get-galera
        image: {{ .Values.mariadb.statestore.image }}
        command: ["/bin/sh"]
        args: ["-c", "cd /root; node ./client.js galera-init {{ .Release.Name }}-mdb-state /mnt/config-map"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: mariadb-config-vol
            mountPath: /mnt/config-map
          - name: mariadb-configtemplate-vol
            mountPath: /mnt/config-template

      # runs an initialization script to prepare the correct startup configuration
      - name: init-galera
        image: {{ .Values.mariadb.server.image }}
        command:
          - bash
          - /mnt/config-template/init-configurations.sh
          - galera
        env:
        - name: RESTORE_FROM_FOLDER
          value: {{ .Values.mariadb.server.restore.restoreFrom }}
        - name: CLUSTER_TOPOLOGY
          value: {{ .Values.mariadb.cluster.topology }}
        - name: RELEASE_NAME
          value: {{ .Release.Name }}
        - name: CLUSTER_ID
          value: "{{ .Values.mariadb.cluster.id }}"
        volumeMounts:
          - name: mariadb-secrets-vol
            mountPath: /mnt/secrets
            readOnly: true
          - name: mariadb-entrypoint-vol
            mountPath: /docker-entrypoint-initdb.d
          - name: mariadb-configtemplate-vol
            mountPath: /mnt/config-template
          - name: mariadb-config-vol
            mountPath: /mnt/config-map

      containers:
      - name: mariadb-server
        image: {{ .Values.mariadb.server.image }}
        command:
        # start a mariadb instance
        - bash
        - /mnt/config-map/start-mariadb-instance.sh
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "Y"
        - name: RESTORE_FROM_FOLDER
          value: {{ .Values.mariadb.server.restore.restoreFrom }}
        - name: CLUSTER_TOPOLOGY
          value: {{ .Values.mariadb.cluster.topology }}
        ports:
        - containerPort: 3306
{{ tpl (.Files.Get "snippets/resources") . | indent 8 }}
        volumeMounts:
        {{- if .Values.mariadb.backup.target.server }}
        - name: backup-data-storage
          mountPath: /backup-storage
        {{- end }}
        - name: mariadb-entrypoint-vol
          mountPath: /docker-entrypoint-initdb.d
        - name: mariadb-config-vol
          mountPath: /mnt/config-map
        # a permanent volume for data storage
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: mariadb-socket-vol
          mountPath: /var/run/mysqld
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1

      # runs a state store client to ensure the state is being maitained
      - name: state
        image: {{ .Values.mariadb.statestore.image }}
        command: ["/bin/sh"]
        args: ["-c", "cd /root; node ./client.js galera {{ .Release.Name }}-mdb-state /mnt/config-map"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: mariadb-configtemplate-vol
            mountPath: /mnt/config-template

{{ tpl (.Files.Get "snippets/backup") . | indent 6 }}

      restartPolicy: Always

      volumes:
      {{- if .Values.mariadb.backup.target.server }}
      - name: backup-data-storage
        nfs:
          server: {{ .Values.mariadb.backup.target.server }}
          path: {{ .Values.mariadb.backup.target.path }}
        capacity:
          storage: 1Mi
        accessModes:
          - ReadWriteMany
      {{- end }}
      - name: mariadb-entrypoint-vol
        emptyDir: {}
      - name: mariadb-config-vol
        emptyDir: {}
      - name: mariadb-configtemplate-vol
        configMap:
          name: {{ .Release.Name }}-mariadb-config
      - name: mariadb-secrets-vol
        secret:
          secretName: {{ .Release.Name }}-mariadb-secret
      - name: mariadb-socket-vol
        emptyDir: {}

  # ensures persistent volumes end up on the same pod
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        mariadb: {{ .Release.Name }}
        storage.mariadb: {{ .Release.Name }}
        {{- if .Values.mariadb.cluster.id }}
        id.mariadb: "{{ .Values.mariadb.cluster.id }}"
        {{- end }}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.mariadb.server.storage.size }}
      {{- if .Values.mariadb.server.storage.class }}
      storageClassName: {{ .Values.mariadb.server.storage.class }}
      {{- end }}
