# Copyright (C) 2018, MariaDB Corporation
#
# Stores cluste-wide initialization scripts in a config map

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mariadb-config
  labels:
    mariadb: {{ .Release.Name }}
    id.mariadb: "{{ .Values.mariadb.cluster.id }}"
data:
  init-configurations.sh: |
{{ tpl (.Files.Get "config/init-configurations.sh") . | indent 4 }}

  start-mariadb-instance.sh: |
{{ tpl (.Files.Get "config/start-mariadb-instance.sh") . | indent 4 }}

  users.sql: |
{{ tpl (.Files.Get "config/users.sql") . | indent 4 }}

  maxscale.cnf: |
{{ tpl (.Files.Get "config/maxscale.cnf") . | indent 4 }}

{{- if or (eq .Values.mariadb.cluster.topology "standalone") (eq .Values.mariadb.cluster.topology "masterslave") }}
  replication.sql: |
{{ tpl (.Files.Get "config/replication.sql") . | indent 4 }}
{{- else if eq .Values.mariadb.cluster.topology "galera" }}
  galera.cnf: |
{{ tpl (.Files.Get "config/galera.cnf") . | indent 4 }}
{{- end }}

{{- if .Values.mariadb.server.backup.claimName }}
  backup-restore.sh: |
{{ tpl (.Files.Get "config/backup-restore.sh") . | indent 4 }}
{{- end }}
