apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mdb-nfs
spec:
  selector:
    nfs.mariadb: {{ .Release.Name }}
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed, but it doesn't work wothout one
    port: 1234
    targetPort: 1234
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mdb-nfs
  labels:
{{ tpl (.Files.Get "snippets/labels.yaml") . | indent 4 }}
    nfs.mariadb: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      nfs.mariadb: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}-mdb-nfs
  replicas: 1
  template:
    metadata:
      labels:
        nfs.mariadb: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nfs
        image: itsthenetwork/nfs-server-alpine
        env:
        - name: SHARED_DIRECTORY
          value: /nfs
        volumeMounts:
        - name: data
          mountPath: /nfs
        securityContext:
          privileged: true
      volumes:
      - name: data
        emptyDir: {}