# Copyright (C) 2018, MariaDB Corporation
#
# Stores cluste-wide initialization scripts in a config map

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mariadb-config
  labels:
    mariadb: {{ .Release.Name }}
    id.mariadb: "{{ .Values.ID }}"
data:
  init-configurations.sh: |
{{ tpl (.Files.Get "config/init-configurations.sh") . | indent 4 }}

  start-mariadb-instance.sh: |
{{ tpl (.Files.Get "config/start-mariadb-instance.sh") . | indent 4 }}

  users.sql: |
{{ tpl (.Files.Get "config/users.sql") . | indent 4 }}

  maxscale.cnf: |
{{ tpl (.Files.Get "config/maxscale.cnf") . | indent 4 }}

{{ if or (eq .Values.TEMPLATE "standalone") (eq .Values.TEMPLATE "masterslave") }}
  replication.sql: |
{{ tpl (.Files.Get "config/replication.sql") . | indent 4 }}
{{ else if eq .Values.TEMPLATE "galera" }}
  galera.cnf: |
{{ tpl (.Files.Get "config/galera.cnf") . | indent 4 }}
{{ end }}
