# Copyright (C) 2018, MariaDB Corporation
#
# Defines a HA maxscale cluster as a deployment fronted
# by a load-balancer service that is also the client endpoint. 
# Only one MaxScale instance will be active at a time.
# Allows scaling the number of MaxScale instances by running:
# kubectl scale deployment <lavel>-mdb-mxs --replicas=<number of instances> 

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
  labels:
    mariadb: {{ .Release.Name }}
    id.mariadb: "{{ .Values.ID }}"
    entrypoint.mariadb: {{ .Release.Name }}
spec:
  ports:
  - name: maxscale-readwrite
    port: 4006
    targetPort: 4006
  - name: maxscale-readonly
    port: 4008
    targetPort: 4008
  selector:
    maxscale.mariadb: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mdb-mxs
  labels:
    mariadb: {{ .Release.Name }}
    id.mariadb: "{{ .Values.ID }}"
    maxscale.mariadb: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      mariadb: {{ .Release.Name }}
      maxscale.mariadb: {{ .Release.Name }}
  replicas: {{ .Values.INITIAL_COUNT_MAXSCALE }}
  template:
    metadata:
      labels:
        mariadb: {{ .Release.Name }}
        maxscale.mariadb: {{ .Release.Name }}
    spec:
      initContainers:
      - name: init-maxscale
        image: {{ .Values.MARIADB_SERVER_IMAGE }}
        command:
          - bash
          - /mnt/config-template/init-configurations.sh
          - maxscale
        volumeMounts:
          - mountPath: /mnt/secrets
            name: mariadb-secrets-vol
            readOnly: true
          - mountPath: /mnt/config-template
            name: mariadb-configtemplate-vol
          - mountPath: /etc/maxscale-cfg
            name: mariadb-config-vol
      containers:
      - image: {{ .Values.MARIADB_STATESTORE_IMAGE }}
        command: ["/bin/sh"]
        args: ["-c", "cd /root; node ./client.js maxscale {{ .Release.Name }}-mdb-state"]
        imagePullPolicy: IfNotPresent
        name: state
        volumeMounts:
          - name: mariadb-configtemplate-vol
            mountPath: /mnt/config-template
      - args:
        - maxscale
        - -d
        - -U
        - maxscale
        - --configdir=/etc/maxscale-cfg
        image: {{ .Values.MARIADB_MAXSCALE_IMAGE }}
        name: maxscale
        ports:
        - containerPort: 4006
        - containerPort: 4008
        resources: {}
        volumeMounts:
        - mountPath: /etc/maxscale-cfg
          name: mariadb-config-vol
      restartPolicy: Always
      volumes:
      - name: mariadb-config-vol
        emptyDir: {}
      - name: mariadb-configtemplate-vol
        configMap:
          name: {{ .Release.Name }}-mariadb-config
      - name: mariadb-secrets-vol
        secret:
          secretName: {{ .Release.Name }}-mariadb-secret
